runtime: nodejs20

handlers:
# Force HTTPS and add security headers
- url: /
  static_files: index.html
  upload: index.html
  secure: always
  http_headers:
    Strict-Transport-Security: "max-age=31536000; includeSubDomains"
    X-Content-Type-Options: "nosniff"
    X-Frame-Options: "SAMEORIGIN"
    X-XSS-Protection: "1; mode=block"

- url: /styles.css
  static_files: styles.css
  upload: styles.css
  secure: always

- url: /app.js
  static_files: app.js
  upload: app.js
  secure: always

- url: /.*
  static_files: index.html
  upload: index.html
  secure: always
  http_headers:
    Strict-Transport-Security: "max-age=31536000; includeSubDomains"
    X-Content-Type-Options: "nosniff"
    X-Frame-Options: "SAMEORIGIN"
    X-XSS-Protection: "1; mode=block"