#!/bin/bash

echo "🚀 Simple deployment options for your landing page:"
echo ""
echo "Option 1: Use Netlify Drop (Immediate deployment)"
echo "==========================================="
echo "1. Open https://app.netlify.com/drop"
echo "2. Drag and drop this folder: /Users/pukhraj/Desktop/CL/v1"
echo "3. Get instant URL, then add custom domain cargolynx.io"
echo ""
echo "Option 2: Use Vercel (Best for custom domains)"
echo "==========================================="
echo "1. Install Vercel CLI: npm i -g vercel"
echo "2. Run: vercel --prod"
echo "3. Follow prompts to deploy"
echo "4. Add custom domain in Vercel dashboard"
echo ""
echo "Option 3: Fix GCP Permissions"
echo "============================="
echo "Ask your GCP admin to run:"
echo "gcloud projects add-iam-policy-binding cargolynx-main \\"
echo "  --member='serviceAccount:cargolynx-main@appspot.gserviceaccount.com' \\"
echo "  --role='roles/storage.admin'"
echo ""
echo "Then run: gcloud app deploy app.yaml"
echo ""
echo "All options provide free SSL certificates!"