#!/bin/bash

echo "🔧 Fixing Redirect Loop for cargolynx.io"
echo "========================================"
echo ""

echo "1️⃣ Current Issues:"
echo "- Redirect loop detected on cargolynx.io"
echo "- This usually happens when:"
echo "  • Domain registrar redirects to www"
echo "  • Firebase redirects back to non-www"
echo "  • OR SSL redirect conflicts"
echo ""

echo "2️⃣ Redeploying with fixed configuration..."
firebase deploy --only hosting --project cargolynx-main

echo ""
echo "3️⃣ Domain Configuration Check:"
echo "================================"
echo ""
echo "Please verify these settings:"
echo ""
echo "A) In your Domain Registrar (where you bought cargolynx.io):"
echo "   - Remove any redirects to www"
echo "   - Use only A records or CNAME as provided by Firebase"
echo "   - Don't use any forwarding/redirect features"
echo ""
echo "B) Firebase Console Domain Setup:"
echo "   Go to: https://console.firebase.google.com/project/cargolynx-main/hosting/sites"
echo "   - Click on your domain"
echo "   - Verify status is 'Connected'"
echo "   - Check that both cargolynx.io and www.cargolynx.io are added"
echo ""

echo "4️⃣ DNS Records Should Be:"
echo "=========================="
echo "For apex domain (cargolynx.io):"
echo "Type: A"
echo "Name: @"
echo "Value: (Firebase IPs)"
echo "  151.101.1.195"
echo "  151.101.65.195"
echo ""
echo "For www subdomain:"
echo "Type: CNAME"
echo "Name: www"
echo "Value: cargolynx-main.web.app"
echo ""

echo "5️⃣ Quick Fixes to Try:"
echo "======================="
echo "1. Clear DNS cache:"
echo "   - Mac: sudo dscacheutil -flushcache"
echo "   - Windows: ipconfig /flushdns"
echo ""
echo "2. Test without www:"
echo "   https://cargolynx.io"
echo ""
echo "3. Test with www:"
echo "   https://www.cargolynx.io"
echo ""
echo "4. Test Firebase default domain (should always work):"
echo "   https://cargolynx-main.web.app"
echo ""

echo "6️⃣ If Still Having Issues:"
echo "=========================="
echo "- Check Cloudflare/DNS provider for redirect rules"
echo "- Temporarily remove custom domain and re-add it"
echo "- Contact Firebase support with error details"
echo ""

echo "Current deployment status:"
firebase hosting:sites:list